### PR TITLE
Fix windows node file eof read

### LINKED ISSUE #3282: Test other.test_stdin fails on Windows.
Running the test `other.test_stdin` on Windows fails with

```
======================================================================
ERROR: test_stdin (test_other.other)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "G:\slaves\emcc\win-incoming\build\emscripten\tests\test_other.py", line 1257, in test_stdin
    self.assertContained('abcdef\nghijkl\neof', open('out.txt').read())
  File "G:\slaves\emcc\win-incoming\build\emscripten\tests\runner.py", line 353, in assertContained
    additional_info
Exception: Expected to find 'abcdef
ghijkl
eof' in 'abcdef
ghijkl
error 1

', diff:

--- expected
+++ actual
@@ -1,3 +1,5 @@
 abcdef
 ghijkl
-eof
+error 1
+
+
```

What happens is that instead of receiving `feof`, the C code gets `ferror` raised. Not sure if this is due to a node.js incompatibility, a bug, or some issue in how the Emscripten FS calls to node.js.

### PR DESCRIPTION
**Pull request by juj**
Node.js has cross-platform behavioral differences that on Windows, fs.readSync() will throw an EOF exception when at end of file, but on Linux and OS X, the read will just return `null`. This would cause `EPERM` errno on Windows when trying to read end of file. Fix by catching the error and adapting to the expected null return behavior. Fixes #3282.

Also fixes dirty behavior that on Windows in node.js, the stdin read code would attempt to read hardcoded file `C:\dev\stdin`.

### CODE REVIEW

File: src/library_tty.js [hunk 1]
```diff
@@ -100,15 +100,26 @@ mergeInto(LibraryManager.library, {
...
+              } catch (e) {}
+            }
 
-            bytesRead = fs.readSync(fd, buf, 0, BUFSIZE, null);
+            try {
+              bytesRead = fs.readSync(fd, buf, 0, BUFSIZE, null);
+            } catch(e) {
+              // Cross-platform differences: on Windows, reading EOF throws an exception, but on other OSes,
+              // reading EOF returns 0. Uniformize behavior by treating the EOF exception to return 0.
+              if (e.toString().indexOf('EOF') != -1) bytesRead = 0;
```
Comment (kripken) [inline src/library_tty.js]: We could add a check on isPosixPlatform to be sure, perhaps? But I'm ok either way, lgtm.

Comment (juj) [inline src/library_tty.js]: I thought about that as well, but I suppose shouldn't be any harm to have in both, and prefer having as few extra chars of code here as possible. Node.js file system documentation at https://nodejs.org/api/fs.html doesn't seem to define EOF behavior at all (or I couldn't find any), so not sure which one would be the designed behavior. Posted this up at https://github.com/nodejs/node/issues/8024, folks there can probably chime in on that.
