### PR TITLE
Fix wasm loading in workers, and refactor async promise code

### LINKED ISSUE #5005: emscripten_create_worker with -s WASM=1
Using sdk-incoming-64bit, binaryen-master-64bit as per http://webassembly.org/getting-started/developers-guide/.

Calling `emscripten_create_worker("wasm_worker.js")` consistently fails due to `Module['wasmBinary']` not being set.

As a temporary workaround I've created the following stub:
```
// wasm_worker_loader.js
var xhr = new XMLHttpRequest();
xhr.open('GET', 'wasm_worker.wasm', false);
xhr.responseType = 'arraybuffer';
xhr.send(null);
var Module = {'wasmBinary': xhr.response};
importScripts('wasm_worker.js');
```

### PR DESCRIPTION
**Pull request by kripken**
Fixes #5005. Specifically, this

 * Adds readBinary support in web workers, as they can do sync binary xhrs after all, so that fixes #5005.
 * Refactor a getBinaryPromise method that gets a promise, no matter which platform we are on. In particular, on a worker (which lacks the Fetch API), it can use that readBinary method.

### CODE REVIEW

**Comment by kripken** [comment]
I realized as a nice benefit of this refactoring that we can get rid of the ugly preloading of the wasm binary into Module.wasmBinary in emcc. (And that made me notice some bugs in this PR, since it was just using the preloaded binary... fixed).

File: src/preamble.js [hunk 1]
```diff
@@ -2212,7 +2224,9 @@ function integrateWasmJS(Module) {
 #if BINARYEN_ASYNC_COMPILATION
     Module['printErr']('asynchronously preparing wasm');
     addRunDependency('wasm-instantiate'); // we can't run yet
-    WebAssembly.instantiate(getBinary(), info).then(function(output) {
+    getBinaryPromise().then(function(binary) {
+      return WebAssembly.instantiate(binary, info)
+    }).then(function(output) {
```
Comment (juj) [inline src/preamble.js]: Hey, since working on this, can you change the #if #endif in here to a #if #else #endif to avoid the "unreachable code" console warnings below?

File: src/preamble.js [hunk 2]
```diff
@@ -2212,7 +2224,9 @@ function integrateWasmJS(Module) {
 #if BINARYEN_ASYNC_COMPILATION
     Module['printErr']('asynchronously preparing wasm');
     addRunDependency('wasm-instantiate'); // we can't run yet
-    WebAssembly.instantiate(getBinary(), info).then(function(output) {
+    getBinaryPromise().then(function(binary) {
```
Comment (juj) [inline src/preamble.js]: The main .html file is supposed to download the .wasm file. At this point' is it not possible that the .wasm file download is still in progress, but has not finished yet, and therefore `getBinaryPromise()` will kick off a second parallel download redundantly?

File: src/preamble.js [hunk 3]
```diff
@@ -2153,16 +2153,28 @@ function integrateWasmJS(Module) {
 
   function getBinary() {
```
Comment (juj) [inline src/preamble.js]: Do we still need this getBinary() function as well, or could we just have one getBinaryPromise() function that also contains the content of this function?

File: src/preamble.js (hunk 1 above)
Comment (kripken) [inline src/preamble.js]: Good idea, fixing.

File: src/preamble.js (hunk 2 above)
Comment (kripken) [inline src/preamble.js]: Not as it currently works - the html downloads the wasm binary *before* starting to do anything else. Another reason it's good to get rid of that thing ;)

File: src/preamble.js (hunk 3 above)
Comment (kripken) [inline src/preamble.js]: We use it when we need synchronous access to it - for the interpreter, or when async compilation is off. Also, I think it's nice it's separate, conceptually.

**Comment by kripken** [comment]
ping @juj, see responses to comments above, i think this is good to go unless you have further issues.

**Comment by kripken** [comment]
re-ping @juj

**Comment by juj** [comment]
Looks alright to me - the use of the `fetch` api will preclude iOS Safari (http://caniuse.com/#search=fetch), oddly desktop Safari has that already. Though hopefully by the time Webkit adds wasm support, they'd have fetch as well.

**Comment by kripken** [comment]
Good to know about fetch, when they ship wasm on iOS we'll need to track that.
