### PR TITLE
Fix redundant functions reassignment

### LINKED ISSUE #5461: Module['_sbrk'] reassignment
With `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[] -s WASM=1` the code I'm getting contains following piece:
```javascript
  function ___setErrNo(value) {
      if (Module['___errno_location']) HEAP32[((Module['___errno_location']())>>2)]=value;
      return value;
    } 
  Module["_sbrk"] = _sbrk;
DYNAMICTOP_PTR = allocate(1, "i32", ALLOC_STATIC);

STACK_BASE = STACKTOP = Runtime.alignMemory(STATICTOP);

STACK_MAX = STACK_BASE + TOTAL_STACK;
....
var _sbrk = Module["_sbrk"] = function() { return Module["asm"]["_sbrk"].apply(null, arguments) };
```

In particular I'm interested in `Module["_sbrk"] = _sbrk;` piece and `var _sbrk = Module["_sbrk"]` few lines below it.

I've tried to find where it comes from and why is even needed. It comes from [this line](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/emscripten.py#L506), from `metadata['declares']`, then through [this line](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/src/jsifier.js#L78) it gets printed [here](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/src/jsifier.js#L388).

Can anyone tell me why is it there and why needed?
For me it doesn't make any sense.

I'm working on a way to reduce build size a bit, but this piece causes issues with final build, since after changes I'm doing `var _sbrk` is not present anymore (while `Module["_sbrk"]` is still there). Since `_sbrk` is not used anywhere else, I'd like to make it disappear.

### PR DESCRIPTION
**Pull request by nazar-pc**
Together with #5463 fixes #5461

### CODE REVIEW

**Comment by kripken** [comment]
Did you run the test suite? I'd verify at least `default, asm2,` and `other` pass.

**Comment by nazar-pc** [comment]
Initial fix was indeed incorrect, I've changed it and run `default`, `asm2` and `other`. There are some errors, probably, because of my local environment, but they are exactly the same as on `incoming` branch (tests were executed on each branch and output was compared), so no regressions were introduced by this patch.

File: src/jsifier.js [hunk 1]
```diff
@@ -241,7 +241,7 @@ function JSify(data, functionsOnly) {
         EXPORTED_FUNCTIONS[finalName] = 1;
         Functions.libraryFunctions[finalName] = 2;
       }
-      if ((EXPORT_ALL || (finalName in EXPORTED_FUNCTIONS)) && !noExport) {
+      if (EXPORT_ALL && !(finalName in EXPORTED_FUNCTIONS) && !noExport) {
```
Comment (kripken) [inline src/jsifier.js]: Interesting, so this line is only needed for EXPORT_ALL? But normal exporting is done elsewhere? Looks like not in this file, so I am guessing in emscripten.py.

This looks like a good change to me, I'm running some local tests and will merge assuming all is good. We can probably do even better though by moving the EXPORT_ALL logic into emscripten.py, that might be worth investigating.

Comment (nazar-pc) [inline src/jsifier.js]: Yes, correct assignment is done in emscripten.py. There are 2 similar places:
https://github.com/kripken/emscripten/blob/5387c1e5f1f55b69c41b94cf044062c59e052f0b/emscripten.py#L889-L893
https://github.com/kripken/emscripten/blob/5387c1e5f1f55b69c41b94cf044062c59e052f0b/emscripten.py#L1610-L1614

When the lines generated by the code moved by this PR is executed, variables on the right side from `=` are `undefined` anyway and actually defined later by linked code from emscripten.py mentioned above.

I'm not sure, however, that this code should be moved to emscripten.py, since `!(finalName in EXPORTED_FUNCTIONS)` functions are generated earlier in the process (haven't checked when and where exactly). Basically this function loops through many functions, both explicitly exported by user and those used internally. It is beyond my understanding of the project at the moment.

Comment (kripken) [inline src/jsifier.js]: Got it, thanks. Yeah, maybe this code is fine where it is.

Ok, looks like tests passed here, great, so merging.
