### PR TITLE
Export FS objects on Module

### LINKED ISSUE #3690: Get FS object by its name
Is there a way to get FS object by its name (`"NODEFS"`, `"IDBFS"`, etc) in order to pass it to `FS.mount` using something better than the following if/switch?

```js
var fs;
if (type == "NODEFS") {
  fs = NODEFS;
} else if (type == "IDBFS") {
  fs = IDBFS;
}
```

`eval` doesn't work in case of Closure because it minifies the names. Can we put FS objects to some dict if the answer is no?

### PR DESCRIPTION
**Pull request by Kagami**
Fixes #3690

I'm not sure it's the best way. Just one of the variants that should work for me.

### CODE REVIEW

File: src/library_fs.js [hunk 1]
```diff
@@ -1,6 +1,10 @@
 mergeInto(LibraryManager.library, {
   $FS__deps: ['$ERRNO_CODES', '$ERRNO_MESSAGES', '__setErrNo', '$PATH', '$TTY', '$MEMFS', '$IDBFS', '$NODEFS', 'stdin', 'stdout', 'stderr'],
   $FS__postset: 'FS.staticInit();' +
+                'Module["FS"] = Object.create(null);' +
```
Comment (kripken) [inline src/library_fs.js]: Let's put it on the FS object itself. We can set these values in `staticInit`, something like

````
  FS.filesystems = {
    'MEMFS' : MEMFS,
    ..
  };
````

Putting it on module is risky, as something else called "FS" might be there - the FS object itself, in fact, if the user asked to export it.

Side note, why not do `{}` instead of `Object.create(null)`? I'm not aware of benefits to the longer form.

Comment (Kagami) [inline src/library_fs.js]: >Let's put it on the FS object itself

You're right, that's better. Fixed.

>Side note, why not do {} instead of Object.create(null)

To make `in` work without excesses (e.g. `'toString' in FS.filesystems`, `'__proto__' in FS.filesystems`). Though I'm ok with the current variant too.

File: src/library_fs.js [hunk 2]
```diff
@@ -1347,6 +1347,13 @@ mergeInto(LibraryManager.library, {
       FS.createDefaultDirectories();
       FS.createDefaultDevices();
       FS.createSpecialDirectories();
+
+      FS.filesystems = {
```
Comment (kripken) [inline src/library_fs.js]: please also define the `filesystems` property on the object itself, with value `null`. That avoids the JS engines seeing a new property being added here, which can cause reoptimization.

Comment (Kagami) [inline src/library_fs.js]: Fixed.
