### PR TITLE
Fetch API headers implementation

### LINKED ISSUE #6359: Memory-leak in fetch API
Hey,
I'm using the emscripten fetch API and it looks like that the memory for each downloaded file is never released. In order to have a reproducible example, I boiled it down to a minimal example,
where files with the following urls are downloaded:

http://localhost/data/1.bin
http://localhost/data/2.bin
...
http://localhost/data/2047.bin

Even if one waits for half an hour, the memory is not released. The sample example written
in JavaScript with XHR request does not have this issue.
Am I doing something wrong?
Thanks for any help. 

```cpp
// compiled with: emcc -s FETCH=1 main.cpp -o index.html
#include <emscripten/fetch.h>

#include <cstdio>
#include <cstring>
#include <vector>
#include <string>

const std::size_t NUM = 2048;
const std::string baseURL = "http://localhost/data/";

void fetchData(std::string url, int fileIdx);

void downloadSucceeded(emscripten_fetch_t *fetch)
{
    printf("Received '%s'\n", fetch->url);

    int fileIdx = int(fetch->userData) + 1;
    emscripten_fetch_close(fetch); // Free data associated with the fetch.

    if(fileIdx < NUM)
        fetchData(baseURL + std::to_string(fileIdx) + ".bin", fileIdx);
}

void downloadFailed(emscripten_fetch_t *fetch)
{
  printf("[ERROR]: %s FAILED!!!\n", fetch->url);
  emscripten_fetch_close(fetch);
}


void fetchData(std::string url, int fileIdx)
{
    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);
    std::strcpy(attr.requestMethod, "GET");
    attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
    attr.onsuccess = downloadSucceeded;
    attr.onerror = downloadFailed;
    attr.userData = (void*)fileIdx;
    emscripten_fetch(&attr, url.c_str());
}

int main()
{
    printf("Start...\n");
    fetchData(baseURL + "1.bin", 1);

    return 0;
}
```

### PR DESCRIPTION
**Pull request by abcthomas**
This pull request combines the work done in pull requests #5619 & #6207 to fix issue #5865.

This may also fix #6359.

### CODE REVIEW

File: system/include/emscripten/fetch.h [hunk 1]
```diff
@@ -93,8 +93,10 @@ typedef struct emscripten_fetch_attr_t
 
 	// If non-zero, specifies a pointer to the data that is to be passed as the body (payload) of the request
 	// that is being performed. Leave as zero if no request body needs to be sent.
-	// The memory pointed to by this field is provided by the user, and needs to be valid only until the call to
-	// emscripten_fetch() returns.
+    // The memory pointed to by this field is provided by the user, and needs to be valid throughout the
```
Comment (kripken) [inline system/include/emscripten/fetch.h]: Looks like there might be spaces mixed with tabs, given the indentation looks wrong? Please use only spaces.

**Comment by kripken** [comment]
@juj, do you have time to review this?

File: system/include/emscripten/fetch.h (hunk 1 above)
Comment (abcthomas) [reply system/include/emscripten/fetch.h]: Yeah sorry not sure why that is, should all be spaces, I'll have a check through

Comment (abcthomas) [reply system/include/emscripten/fetch.h]: I think the actual issue is I'm using spaces but the original file is tabs.

**Comment by abcthomas** [comment]
@kripken is there any chance you can review this ? We had the same issue previously on #5619 of @juj not being available for code review, but you mentioned being able to do it yourself in order to speed things up a little

**Comment by kripken** [comment]
I can try to review it, yeah.

The spacing issues make it hard, though. Can you please change those files to be all spaces, no tabs?

Also please merge incoming, those test errors are hopefully something that was fixed meanwhile.

File: system/include/emscripten/fetch.h (hunk 1 above)
Comment (juj) [reply system/include/emscripten/fetch.h]: Can we change then this PR to use also tabs to stay with the existing style of surrounding code?

(And then adhering to spaces convention could be done in a separate "style change only" PR, because such changes wreak havoc on the changed lines in the PR, and also on Git Blame history. So such changes would be good to be done in a commit/PR of its own.)

File: system/include/emscripten/fetch.h [hunk 2]
```diff
@@ -93,8 +93,10 @@ typedef struct emscripten_fetch_attr_t
...
+	// duration of the fetch operation. If passing a non-zero pointer into this field, make sure to implement
+	// the onsuccess and onerror handlers to be notified when the fetch finishes to know when this memory
```
Comment (juj) [inline system/include/emscripten/fetch.h]: Could this line stress the need to implement both the handlers, e.g. with `make sure to implement *both* the onsuccess and onerror handlers`.

File: system/lib/fetch/emscripten_fetch.cpp [hunk 3]
```diff
@@ -66,16 +68,58 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
 	}
 
 	emscripten_fetch_t *fetch = (emscripten_fetch_t *)malloc(sizeof(emscripten_fetch_t));
+    if ( !fetch ) return 0;
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: The convention is to have parentheses hug the content inside, i.e. ` if (!fetch)`

File: system/lib/fetch/emscripten_fetch.cpp [hunk 4]
```diff
@@ -66,16 +68,58 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
...
+        return 0;
+    }
 	fetch->__attributes = *fetch_attr;
-	fetch->__attributes.destinationPath = fetch->__attributes.destinationPath ? strdup(fetch->__attributes.destinationPath) : 0; // TODO: free
-	fetch->__attributes.userName = fetch->__attributes.userName ? strdup(fetch->__attributes.userName) : 0; // TODO: free
-	fetch->__attributes.password = fetch->__attributes.password ? strdup(fetch->__attributes.password) : 0; // TODO: free
-	fetch->__attributes.requestHeaders = 0;// TODO:strdup(fetch->__attributes.requestHeaders);
-	fetch->__attributes.overriddenMimeType = fetch->__attributes.overriddenMimeType ? strdup(fetch->__attributes.overriddenMimeType) : 0; // TODO: free
+
+#define SAFE_STRDUP(s)                  \
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: Instead of `SAFE_STRDUP`, how about `STRDUP_OR_ABORT`? The word `SAFE` is somewhat vague.

File: system/lib/fetch/emscripten_fetch.cpp [hunk 5]
```diff
@@ -66,16 +68,58 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
...
+    }                                   \
+  }
+
+    SAFE_STRDUP( fetch->__attributes.destinationPath );
+    SAFE_STRDUP( fetch->__attributes.userName );
+    SAFE_STRDUP( fetch->__attributes.password );
+    if ( fetch->__attributes.requestHeaders )
+    {
+        size_t headersCount;
+        for ( headersCount = 0; fetch->__attributes.requestHeaders[ headersCount ]; ++headersCount );
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: This block would read more idiomatic as

```c++
size_t headersCount = 0;
while(fetch->__attributes.requestHeaders[headersCount]) ++headersCount;
```

to point the reader's attention to that the incrementing `headersCount` is the intent, rather than a side effect? A for with `;` at the end of the same line can be subtly overlooked.

File: system/lib/fetch/emscripten_fetch.cpp [hunk 6]
```diff
@@ -66,16 +68,58 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
...
+            return 0;
+        }
+        for ( size_t i = 0; i < headersCount; ++i )
+        {
+            headers[ i ] = strdup( fetch->__attributes.requestHeaders[ i ] );
+            if ( !headers[ i ] )
+            {
+                emscripten_fetch_free( fetch );
+                return 0;
+            }
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: Looks like this could also use the `SAFE_STRDUP`/`STRDUP_OR_ABORT` function.

File: system/lib/fetch/emscripten_fetch.cpp [hunk 7]
```diff
@@ -66,16 +68,58 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
...
+        }
+        headers[ headersCount ] = 0;
+        fetch->__attributes.requestHeaders = headers;
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: Hmm, given that we only assign `fetch->__attributes.requestHeaders` here, the function `emscripten_fetch_free()` does not see any of these `strdup()`ed headers or the `malloc()`ed headers array above, and if any of these allocs fail, this will result in a memory leak.

To do safe cleanup, how about removing the `headers` variable altogether, and immediately assign the `malloc()` on top to `fetch->__attributes.requestHeaders`, grabbing the old pointer to a safe location first, and then immediately after `malloc()`, `memset()` the newly allocated block to zero, and then iterate to `strdup` all the contents? That way `emscripten_fetch_free()` will properly deallocate any partially allocated data on failure.

File: system/lib/fetch/emscripten_fetch.cpp [hunk 8]
```diff
@@ -125,27 +169,44 @@ EMSCRIPTEN_RESULT emscripten_fetch_wait(emscripten_fetch_t *fetch, double timeou
 #endif
 }
 
-EMSCRIPTEN_RESULT emscripten_fetch_close(emscripten_fetch_t *fetch)
+EMSCRIPTEN_RESULT emscripten_fetch_close( emscripten_fetch_t *fetch )
 {
-	if (!fetch) return EMSCRIPTEN_RESULT_SUCCESS; // Closing null pointer is ok, same as with free().
+    if ( !fetch ) return EMSCRIPTEN_RESULT_SUCCESS; // Closing null pointer is ok, same as with free().
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: Here and throughout, it looks like the code is going away from convention, i.e. from `(!fetch)` to `( !fetch )`, but ideally would be the opposite. Also would be good to stick to tabs for now (follow the convention of surrounding code (tm)). And let's do the style changes in a followup PR.

File: system/lib/fetch/emscripten_fetch.cpp [hunk 9]
```diff
@@ -125,27 +169,44 @@ EMSCRIPTEN_RESULT emscripten_fetch_wait(emscripten_fetch_t *fetch, double timeou
...
+        fetch->status = ( unsigned short ) -1;
+        strcpy( fetch->statusText, "aborted with emscripten_fetch_close()" );
+        fetch->__attributes.onerror( fetch );
+    }
+
+    emscripten_fetch_free( fetch );
+    return EMSCRIPTEN_RESULT_SUCCESS;
+}
+
+static void emscripten_fetch_free( emscripten_fetch_t *fetch )
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: We should rename this function to just `fetch_free` instead of `emscripten_fetch_free`, because this function (as signified by `static` also) is not part of the public api, so that by static reading code above, people will not get a misimpression that `emscripten_fetch_free` might be something called from outside.

**Comment by abcthomas** [comment]
@juj Yeah admittedly I haven't actually taken a look at the code just copied it from the other PR's 😄 . Will have plenty of time to go through it today though, thanks for taking the time to review this

File: system/lib/fetch/emscripten_fetch.cpp (hunk 7 above)
Comment (abcthomas) [reply system/lib/fetch/emscripten_fetch.cpp]: I'm not sure if that's possible, `fetch->__attributes.requestHeaders` is a `const * char * const` so we can't directly assign to the individual const elements of the array:

```
const char * const *headers = fetch->__attributes.requestHeaders;
fetch->__attributes.requestHeaders = (const char * const*)malloc((headersCount + 1) * sizeof(const char*));
// ...null checking & memset
for(size_t i = 0; i < headersCount; ++i)
{
    fetch->__attributes.requestHeaders[i] = strdup(headers[i]); // <--- Can't do this
}
```

Instead I can ensure the `headers` array is freed up in the event of a failed alloc ?

**Comment by markmarucot** [comment]
Is there any update on implementing custom header? I’m working on a program that requires sending custom headers.

**Comment by cybermizrach** [comment]
Is there any update on this functionality? I would love to have it implemented. Thank you for all of the great work!

**Comment by abcthomas** [comment]
@juj bump

File: system/lib/fetch/emscripten_fetch.cpp [hunk 10]
```diff
@@ -66,16 +68,65 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
...
+	{									\
+		s = strdup(s);					\
+		if (!s)							\
+		{								\
+			fetch_free(fetch);			\
+			return 0;					\
+		}								\
+	}
+
+	STRDUP_OR_ABORT(fetch->__attributes.destinationPath);
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: Hmm, this is not correct. `fetch->__attributes` is assigned from the original source pointers above at `fetch->__attributes = *fetch_attr;`. If the line `STRDUP_OR_ABORT(fetch->__attributes.destinationPath);` here fails allocation, it calls to `fetch_free(fetch);` and as result, it will `free()` all the fields of `fetch->__attributes`, in particular `fetch->__attributes.userName` and `fetch->__attributes.password` - however these pointers have not been strdupped yet, that is only done on the two subsequent lines. So this means that if this first line needs to abort, the function `fetch_free()` will end up freeing user submitted pointers.

Comment (juj) [reply system/lib/fetch/emscripten_fetch.cpp]: A good way to make this clean would be to remove the line `fetch->__attributes = *fetch_attr;` above, and instead copy the fields one by one:

```
fetch->__attributes.destinationPath = STRDUP_OR_ABORT(fetch_attr->destinationPath);
```

and have `STRDUP_OR_ABORT(s)` not do a `s = strdup(s);` but instead pass out the dupped pointer?

File: system/lib/fetch/emscripten_fetch.cpp [hunk 11]
```diff
@@ -127,25 +178,42 @@ EMSCRIPTEN_RESULT emscripten_fetch_wait(emscripten_fetch_t *fetch, double timeou
...
 #endif
 	// This function frees the fetch pointer so that it is invalid to access it anymore.
 	// Use a few key fields as an integrity check that we are being passed a good pointer to a valid fetch structure,
 	// which has not been yet closed. (double close is an error)
-	if (fetch->id == 0 || fetch->readyState > 4) return EMSCRIPTEN_RESULT_INVALID_PARAM;
+	if(fetch->id == 0 || fetch->readyState > 4) return EMSCRIPTEN_RESULT_INVALID_PARAM;
 
 	// This fetch is aborted. Call the error handler if the fetch was still in progress and was canceled in flight.
-	if (fetch->readyState != 4 /*DONE*/ && fetch->__attributes.onerror)
+	if(fetch->readyState != 4 /*DONE*/ && fetch->__attributes.onerror)
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: These are whitespace changes going away from convention - the convention is to have space between `if` and the parentheses, i.e. `if (`

File: system/lib/fetch/emscripten_fetch.cpp [hunk 12]
```diff
@@ -66,16 +68,65 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
...
+			return 0;					\
+		}								\
+	}
+
+	STRDUP_OR_ABORT(fetch->__attributes.destinationPath);
+	STRDUP_OR_ABORT(fetch->__attributes.userName);
+	STRDUP_OR_ABORT(fetch->__attributes.password);
+	if(fetch->__attributes.requestHeaders)
+	{
+		size_t headersCount;
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: This should be `size_t headersCount = 0;` - local variables are not guaranteed to be zero initialized.

File: system/lib/fetch/emscripten_fetch.cpp [hunk 13]
```diff
@@ -66,16 +68,65 @@ emscripten_fetch_t *emscripten_fetch(emscripten_fetch_attr_t *fetch_attr, const
...
+		{
+			headers[i] = strdup(fetch->__attributes.requestHeaders[i]);
+			if(!headers[i])
+			{
+				for(size_t j = 0; j < i; ++j)
+				{
+					free((void*)headers[j]);
+				}
+				free((void*)headers);
+				fetch_free(fetch);
```
Comment (juj) [inline system/lib/fetch/emscripten_fetch.cpp]: Here also `fetch_free()` will go to free up user submitted `fetch->__attributes.requestHeaders` pointer on failure, so when changing that, it looks like all the fields referring to `fetch->__attributes` should then refer to `fetch_attr` source data directly when copying over the input.

File: tests/fetch/response_headers.cpp [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+        else
+        {
+            printf( "Downloading.. %lld bytes complete.\n", fetch->dataOffset + fetch->numBytes );
+        }
+    };
+
+    attr.onerror = [] ( emscripten_fetch_t *fetch )
+    {
+        printf( "Download failed!\n" );
+        assert( false && "Shouldn't fail!" );
```
Comment (juj) [inline tests/fetch/response_headers.cpp]: The `onerror` handler is good to have a call to `emscripten_fetch_close(fetch);` as well. Even though that should not happen in this test, occassionally people copy paste test code to use as their own basis, so it's good to have this follow the good practice.

**Comment by juj** [comment]
Apologies for the delays. The approach used here is good and sound, looks good to land to me after the above comments are resolved - no need to grab a further review iteration from me, I know my attention is really sadly spotty these days.

**Comment by juj** [comment]
Something accidental happened to this PR on the merge, looks like all files have changed mode from 100644 → 100755 and there's a merge commit in the PR - can you back those up and rebase instead of merge? Typically pull requests would not have merge commits in them.

**Comment by abcthomas** [comment]
Fixed Git hell, should be good to merge

**Comment by abcthomas** [comment]
@kripken I'm not sure why the tests are failing now, not sure if it's something I've done or not

**Comment by kripken** [comment]
The errors are in the fetch tests, so I think they are likely due to changes in this PR.

Do they pass for you locally? I'd compare that to running incoming locally.

**Comment by abcthomas** [comment]
So I'm still very unsure of what's causing these errors, in the CI test logs the ones that have failed all seem to just state no http server activity. 
When I run `browser.test_*`  locally some appear to fail with no information about why, even with `EMCC_DEBUG` enabled. However those same tests pass when run individually, including the new fetch test.

**Comment by kripken** [comment]
Perhaps it's something to do with running an individual test - might be worth seeing how CI does if you tell it to run just one test, or alternatively running all the tests locally.

**Comment by abcthomas** [comment]
So I fixed some issues with the fetch implementation, it's now working as expected with my local test application and most of the tests are now passing. The only one failing now is `test_access_file_after_heap_resize` so I'm going to take a closer look at what's happening inside that test and what could be going wrong.

**Comment by abcthomas** [comment]
This should be good to merge 👍

**Comment by kripken** [comment]
Looks good, thanks @abcthomas!
